cp ./$1 ./blocks-world/$1
cp ./$1 ./blocks-world-noisy/$1
cp ./$1 ./campus/$1
cp ./$1 ./campus-noisy/$1
cp ./$1 ./depots/$1
cp ./$1 ./depots-noisy/$1
cp ./$1 ./driverlog/$1
cp ./$1 ./driverlog-noisy/$1
cp ./$1 ./dwr/$1
cp ./$1 ./dwr-noisy/$1
cp ./$1 ./easy-ipc-grid/$1
cp ./$1 ./easy-ipc-grid-noisy/$1
cp ./$1 ./ferry/$1
cp ./$1 ./ferry-noisy/$1
cp ./$1 ./intrusion-detection/$1
cp ./$1 ./intrusion-detection-noisy/$1
cp ./$1 ./kitchen/$1
cp ./$1 ./kitchen-noisy/$1
cp ./$1 ./logistics/$1
cp ./$1 ./logistics-noisy/$1
cp ./$1 ./miconic/$1
cp ./$1 ./miconic-noisy/$1
cp ./$1 ./rovers/$1
cp ./$1 ./rovers-noisy/$1
cp ./$1 ./satellite/$1
cp ./$1 ./satellite-noisy/$1
cp ./$1 ./sokoban/$1
cp ./$1 ./sokoban-noisy/$1
cp ./$1 ./zeno-travel/$1
cp ./$1 ./zeno-travel-noisy/$1
